<?php
	/*
include_once('views/header.html');
	//include('views/loginBody.html');
	include_once('views/map.html');
	include_once('views/googleFooter.html');
*/	
	include_once('views/templates-reference/loginFBDemo.html');
?>